public class CommonUtilities{
   
    
    // used in DistributorRetailerLinkTrigger
    public static boolean DistributorRetailerLinkInsertBeforeFlag = true;
    public static boolean DistributorRetailerLinkInsertAfterFlag = true;
    public static boolean DistributorRetailerLinkUpdateBeforeFlag = true;
    public static boolean DistributorRetailerLinkUpdateAfterFlag = true;

    // Used in AccountTrigger
    public static boolean AccountTriggerInsertBeforeFlag = true;
    public static boolean AccountTriggerInsertAfterFlag = true;
    public static boolean AccountTriggerUpdateBeforeFlag = true;
    public static boolean AccountTriggerUpdateAfterFlag = true;  
    
}