/*/*******************************************************************************************
 * @Name         LiveAgentControllerTest
 * @Author       Sahil Chaudhry <sahil.chaudhry@juul.com>
 * @Date         03/30/2020
 * @Group        Customer Service
 * @Description  Test class for the live agent
 *******************************************************************************************/
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*   1.0              Sahil         02/17/2020        Initial Creation
*******************************************************************************************/
@IsTest
private class LiveAgentControllerTest {
    @IsTest
    static void testBehavior() {
        LiveAgentController controller = new LiveAgentController();
    }
}